services:
  - type: web
    name: artoftheharbor
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn artoftheharbor.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: artoftheharbor.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: artoftheharbor.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: artoftheharbor-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: MEDIA_ROOT
        value: /opt/render/media
    disk:
      name: media
      mountPath: /opt/render/media
      sizeGB: 1

databases:
  - name: artoftheharbor-db
    plan: free
    databaseName: artoftheharbor
